apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: userservice
        image: rishabhmalhotra/praticeuserservice
        ports:
        - containerPort: 61550
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:  
             name: mysqldbsecret           
             key: password
        - name: collectorEndpoint
          valueFrom:
            configMapKeyRef:
              name: aggregator-config
              key: jaeger.url
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: aggregator-config
              key: db.url      

